### ISSUE TITLE
Basic Stuff Missing?

### ISSUE THREAD

**Issue by Dastano** [Goz3rr/SatisfactorySaveEditor#10]
I miss Iron Plate / Iron Rod from the Crafting. Maybe something messed up? Tried on a old savegame.

**Comment by Goz3rr** [comment]
Do you mean you're not able to craft them? 

I'm not really sure what you mean, could you describe what you did and what you expected to happen?

**Comment by Dastano** [comment]
Yep, not able to craft them in the Bench, I created a new Game and try the unlocks there. Maybe it messed something up.

**Comment by Goz3rr** [comment]
You should at least complete the tutorial (finish the entire hub) before trying the unlock all research option. I'll try and fix that in the near future though.

**Comment by Dastano** [comment]
I did it on my "Main" Game and it removed my Iron Plate and stuff. I started a new Game, to check again, if something mess up. Sorry for the bad description.

**Comment by Dastano** [comment]
Just to Confirm, if you unlock everything with the Cheat, Iron Pipe and Iron Plate get removed from known recepies.

![nomore](https://user-images.githubusercontent.com/197081/54924415-9df82d00-4f0c-11e9-9dd1-5857a701611e.png)

**Comment by Dastano** [comment]
`/Game/FactoryGame/Schematics/Schematic_StartingRecipes.Schematic_StartingRecipes_C`

Just uncomment this and it work flawlessly. Just tested it :)

**Comment by Goz3rr** [comment]
Ah, yeah my mistake. Thanks for pointing out the fix!
