### ISSUE TITLE
Research unlock, doesn't unlock tier 7 milestones.

### ISSUE THREAD

**Issue by FPSHolland** [Goz3rr/SatisfactorySaveEditor#102]
I just used the research unlock, it unlocked the space elevator input, but it says Tier 1 in SE GUI.
after inputting the quantum comp, heavy modular and turbo motor. it only unlocks the tier 7 tab in the research station, I don't get the milestones or any craftable related to tier 7.

All default unlocked research was already done and all milestones up to tier 6 were done before using unlocker.

I'll add some pics if needed.

**Comment by FPSHolland** [comment]
![2019-05-31 14_21_58-Satisfactory](https://user-images.githubusercontent.com/9270080/58705982-123dc980-83b1-11e9-9292-07a988368dfe.png)
![2019-05-31 14_25_24-Satisfactory](https://user-images.githubusercontent.com/9270080/58705983-123dc980-83b1-11e9-8856-7313f3618425.png)
![2019-05-31 14_28_27-Satisfactory](https://user-images.githubusercontent.com/9270080/58705985-123dc980-83b1-11e9-9f91-62a26da1cb18.png)
![2019-05-31 14_28_55-Satisfactory](https://user-images.githubusercontent.com/9270080/58705987-123dc980-83b1-11e9-96aa-8cf37e0d0649.png)
![2019-05-31 14_29_33-Satisfactory](https://user-images.githubusercontent.com/9270080/58705988-123dc980-83b1-11e9-8863-8ea3a61a7b1b.png)
![2019-05-31 14_29_50-Satisfactory](https://user-images.githubusercontent.com/9270080/58705989-12d66000-83b1-11e9-9f4c-0a4c14147e33.png)
![2019-05-31 14_29_58-Satisfactory](https://user-images.githubusercontent.com/9270080/58705990-12d66000-83b1-11e9-806d-2cbb4f65f3dc.png)

**Comment by FPSHolland** [comment]
I have tried doing it in a new save after unlocking tier 1, it has the same results.

**Comment by TrickyReuploads** [comment]
aha

**Comment by FPSHolland** [comment]
"aha"
I guess that means you have enough info to work with for now ;)

**Comment by Ryder17z** [comment]
It should be noted that the train tracks are currently prone to crash the game when building them

**Comment by Goz3rr** [comment]
Because all the hidden research was removed from the game, there isn't really much to unlock anymore besides the cheat stuff and some foundation stuff unless you have an older copy of the game.

**Comment by FPSHolland** [comment]
@Gozo3rr, Good to know then I'll just wait until it comes out on the early access branch then.
