### ISSUE TITLE
Can't increase inventory size

### ISSUE THREAD

**Issue by MartinRichards23** [Goz3rr/SatisfactorySaveEditor#113]
I set the bonus inventory slots to 100 at the start of a new game in experimental but it didn't have any effect.

**Comment by tyler513** [comment]
it wont until you get a bonus inventory unlock.

**Comment by budak7273** [comment]
We should likely close this issue. Since they changed how inventory slot count works, we removed the cheat in https://github.com/Goz3rr/SatisfactorySaveEditor/pull/117.

If you know how to get it working again please let us know.

**Comment by Goz3rr** [comment]
Closing as this isn't anything the save editor can fix
