### ISSUE TITLE
Cheat spawner no longer getting unlocked in experimental

### ISSUE THREAD

**Issue by tyler513** [Goz3rr/SatisfactorySaveEditor#114]
Cheat spawners dont get unlocked with the unlock tech in experimental.

**Comment by budak7273** [comment]
The entire cheat tier has been removed from the game in experimental; they are no longer present to be unlocked.

**Comment by budak7273** [comment]
Contact Brabb3l on the modding discord; progress is being made there on a mod to recreate them.

**Comment by Goz3rr** [comment]
Closing as this isn't anything the save editor can fix
