### ISSUE TITLE
Save editing crashes if you click Add Element in editor

### ISSUE THREAD

**Issue by cengbrecht** [Goz3rr/SatisfactorySaveEditor#116]
In the screenshot, I was trying to add a number after increasing my inventory size. 
May not work in general, but its what I was doing. 

![screenshot 196](https://user-images.githubusercontent.com/1149435/59893322-d091b480-9399-11e9-9577-74ffb7c16741.jpg)

**Comment by thiakil** [comment]
Same issue as OP
[log.txt](https://github.com/Goz3rr/SatisfactorySaveEditor/files/4239032/log.txt)

**Comment by cengbrecht** [comment]
Stale, probably not relevant anymore.
