### ISSUE TITLE
Can't open latest save games

### ISSUE THREAD

**Issue by CaptainRush** [Goz3rr/SatisfactorySaveEditor#120]
it seems since the latest train patches you can't open save games no more. getting this error messages. (see pic). older save games work.

![image](https://user-images.githubusercontent.com/11178766/60396473-5c49d480-9b42-11e9-84a3-311e2dfe3390.png)

**Comment by Goz3rr** [comment]
Could you upload a copy of the save you're trying to use?

**Comment by dragonfire5020** [comment]
Hello, I have the same issue
Maybe you could have a look on it, I also attached my savegame

[mygame.zip](https://github.com/Goz3rr/SatisfactorySaveEditor/files/3432738/mygame.zip)

![Screenshot_8](https://user-images.githubusercontent.com/13822065/61897277-04bb4080-af17-11e9-9027-ff28c046ae4b.png)

**Comment by Goz3rr** [comment]
Thanks, with your save I believe I was able to figure it out. Try version 0.6.6

**Comment by dragonfire5020** [comment]
Seems to work again - thx
