### ISSUE TITLE
Question for v0.6.3

### ISSUE THREAD

**Issue by NeferetKuro** [Goz3rr/SatisfactorySaveEditor#122]
Cheat Spawn are disable on v0.6.3? cause don't have them, the rest works fine :)

**Comment by NeferetKuro** [comment]
Same for v0.6.4 Cheat spawn are disable to :x

**Comment by budak7273** [comment]
If by "Cheat Spawn" you mean the cheat resource spawners and other cheat tier equipment, Coffee Stain removed them from the game a few patches ago. See #114

**Comment by NeferetKuro** [comment]
ok thanks budak7273
