### ISSUE TITLE
Minimap Unlock

### ISSUE THREAD

**Issue by TraySSan** [Goz3rr/SatisfactorySaveEditor#127]
Would you please add a cheat that uncovers the entire map ? I've found the correct string, but it has over a million entries to change and that's just not happening. One way to fix this is by adding a ''Find and Replace'' feature. It shouldn't be that hard to implement, since it's just changing a million zeros to 255s. 
Thanks in advance !

**Comment by Goz3rr** [comment]
Yeah this should be easily doable, I'll look into it
