### ISSUE TITLE
6.6 Crashing in Experimental (6.5 was working until latest update)

### ISSUE THREAD

**Issue by ViralGamer** [Goz3rr/SatisfactorySaveEditor#131]
6.6 Crashing in Experimental (6.5 was working until latest update) ...
I had created a previous save with 6.5 to delete all enemies and also added 3 dogos.
After the latest update to the game, the save still loads but the save editor crashes when I try to import it into the editor.  Went back and tried in 6.5 and it too now crashes on import.

Thanks for your work on this.  

[Exp2_autosave_1.zip](https://github.com/Goz3rr/SatisfactorySaveEditor/files/3437941/Exp2_autosave_1.zip)

**Comment by zoubidabida** [comment]
I can confirm that it crashes while opening a save file with the latest experimental version

**Comment by Goz3rr** [comment]
This should be fixed by the latest released version (0.6.7)
