### ISSUE TITLE
If Mass Dismantle Space Elevator - Game will not let you build a new one.

### ISSUE THREAD

**Issue by ViralGamer** [Goz3rr/SatisfactorySaveEditor#132]
I used Mass Dismantle and just wiped the entire map, which included the Space Elevator.  Now, (after several hours of building a 20 story storage facility tower .. ) I decided to place the Space Elevator at the top.  Game says nope, "You can only build one."  Uh oh.  I guess, when you dismantle it in the game, it must register somewhere that you dismantled it.  Since it was dismantled outside of the game, it was not registered as dismantled so the code thinks I already have one.  I don't.  I'm going to go through my save game file and see if I can find the record.  Will let you know if I have any success.

**Comment by ViralGamer** [comment]
/Game/FactoryGame/-Shared/Blueprint/BP_GameState.BP_GameState_C

mIsSpaceElevatorBuilt was checked

Unchecked it, problem solved!

Leaving this open so that it will be seen and toggle added to script.

**Comment by Ryder17z** [comment]
Related: https://github.com/Goz3rr/SatisfactorySaveEditor/issues/124

**Comment by zebasxx** [comment]
Hi @ViralGamer, I have the same issue after deleting everything with https://satisfactory-calculator.com/ and now I cannot build the Space Elevation... I look for that folder you mention:
/Game/FactoryGame/-Shared/Blueprint/BP_GameState.BP_GameState_C but it do not exist in my computer, do you know how may I fix this? I would appreciate your help.
Regards,
Seba.

**Comment by Goz3rr** [comment]
`/Game/FactoryGame/-Shared/Blueprint/BP_GameState.BP_GameState_C` is not a folder you can find on your PC, it's part of the internal structure of the save file

**Comment by ignamiranda** [comment]
Is there a way to apply this fix nowadays?

**Comment by Ryder17z** [comment]
> Is there a way to apply this fix nowadays?

not directly, no - but you can use the following method to transition to a new save:
1. start a new game using "advanced settings" and pick the correct tier (picking a tier is optional, but sorts out progression, for the most part)
2. save and exit. (do not build anything)
3. go to https://satisfactory-calculator.com/en/interactive-map and load the old save
4. use the selection tools and select the area of buildings to keep by saving it as a "megaprint" 
5. upload the new save to the same site, then load the "megaprint" file, click the button that says "paste in original position"
6. change progression/research settings as necessary, like unlocking things in the "awesome shop"
7. download the modified new savegame
8. enjoy a (probably) fixed save
