### ISSUE TITLE
If you use "unlock all research" then associated  milestones are not removed

### ISSUE THREAD

**Issue by kostermw** [Goz3rr/SatisfactorySaveEditor#133]
I noted that I cannot payoff an active milestone (which was unlocked by using the cheat)
There are 2 elements in [mPaidOffSchematic] and one in [mActiveSchematic] but simply deleting them did not work. Savefile cannot be loaded afterwards.

Correct working save file uploaded (sorry uploaded twice)
[GreenField_102.zip](https://github.com/Goz3rr/SatisfactorySaveEditor/files/3458101/GreenField_102.zip)
[GreenField_102.zip](https://github.com/Goz3rr/SatisfactorySaveEditor/files/3458104/GreenField_102.zip)

**Comment by Ryder17z** [comment]
Related https://github.com/Goz3rr/SatisfactorySaveEditor/issues/126

**Comment by budak7273** [comment]
Closed by 938f1bb. Thank you both for the information. Deleting the properties worked just fine in my testing, and that's exactly what the editor does now; I'm not sure why it was causing errors for you.
