### ISSUE TITLE
InvalidMCPUser

### ISSUE THREAD

**Issue by wasn325** [Goz3rr/SatisfactorySaveEditor#134]
When I change one thing, I get the greeting welcome back invalidmcpuser.

Do you know the Problem?
(I changed one Item in the Inventory)

**Comment by budak7273** [comment]
Is this issue repeatable? It could just be something up with the launcher. Are you using any other mods?

**Comment by wasn325** [comment]
It was repeating, but "repaired it self" (ok I don't know how or why I have no longer the problem).

And I use only this mod

**Comment by budak7273** [comment]
I'm going to close this issue for now. Feel free to reopen it if you encounter the error again and have more details.
