### ISSUE TITLE
0.70 Not loading Exp. Saves

### ISSUE THREAD

**Issue by Baghiel** [Goz3rr/SatisfactorySaveEditor#141]
When attempting to open a save from Experimental, version/build number 106027, it sits there with the grey background and 'Please wait...' but does not do anything else. The program has not crashed or frozen (it still responds when telling it to close), and is not generating any errors or alert boxes.

**Comment by VarianArdell** [comment]
I would assume it has something to do with the experimental version compressing saves to use with cloud storage saving, hopefully this is resolved pretty soon

**Comment by Baghiel** [comment]
Quite probably. Posted here mostly to make sure you were alerted to it, if you weren't already aware.

**Comment by Twente-Mining** [comment]
I'm experiencing the same problem

**Comment by VarianArdell** [comment]
I really hope this gets resolved soon, as I solely play in experimental and would really like to use this with my saves

**Comment by VarianArdell** [comment]
over a week later, cloud/compressed saves are now part of both experimental and main EA versions of Satisfactory, and this issue still hasn't been fixed...

**Comment by AnthorNet** [comment]
Maybe you should have take the time to do a PR and solve your problem? ;)
Just joking, you know people actually do that on their free time....

**Comment by VarianArdell** [comment]
> Maybe you should have take the time to do a PR and solve your problem? ;)
> Just joking, you know people actually do that on their free time....

if I had a clue on how to fix it, I most certainly would have :P I'm just hoping this has at least been seen by someone working on the editor, and are working on a fix

**Comment by budak7273** [comment]
A release that supports the new compressed cloud save format will be out soon. For now, attempting to load one will result in the editor getting stuck on a 'Please wait...' screen. 

The master branch has support for the new format, but we're still testing to see if it corrupts anything before we put out a release.

**Comment by Goz3rr** [comment]
I've released 0.8.0 that should work with compressed cloud, please let me know if you run into any issues with it.
