### ISSUE TITLE
Stuck on Please Wait...

### ISSUE THREAD

**Issue by Sean-McConnachie** [Goz3rr/SatisfactorySaveEditor#143]
Hi there,

save editor was working well for me a couple of days ago. Today I tried to edit an existing map but upon "Open"(ing) of the map the save editor gets stuck on Please Wait... loading screen. I have tried redownloading the complied executable but the issue persisted.

I am using V0.8.0. I tried with V0.7.0 and had the same error which leads me to believe that the error is on my end. Any suggestions as to what it could be?

Cheers,
Sean

**Comment by ElDitcho** [comment]
I have the same issue, worked well for 2 edits and now can't load any of my saves. It stays that way even by deleting the directory

**Comment by ElDitcho** [comment]
ok i just removed the SatisfactorySaveEditor directory in AppData\Local and my saves load again

**Comment by budak7273** [comment]
The most recent update has likely fixed this. Could you please try to open the save again and let us know if it still locks up or errors?

**Comment by Goz3rr** [comment]
Assuming this is fixed since 0.9.0
