### ISSUE TITLE
Unlock Alt Recipes

### ISSUE THREAD

**Issue by bbakermmc** [Goz3rr/SatisfactorySaveEditor#144]
Option to just unlock alternate recipes?

**Comment by budak7273** [comment]
A 'pick what to unlock' screen is in the works that will make this possible. Thank you for your suggetion.

**Comment by budak7273** [comment]
The 'pick what to unlock' screen is coming as a WIP in the rewrite.

**Comment by Goz3rr** [comment]
v0.9.15 added a dialog to select which recipes you want to unlock
