### ISSUE TITLE
ExtractResourses.ps1 doesn't work

### ISSUE THREAD

**Issue by Fyrexia** [Goz3rr/SatisfactorySaveEditor#145]
![image](https://user-images.githubusercontent.com/47077661/68796317-42ec8500-0618-11ea-88cc-a7b9c5727c06.png)

not sure how to fix this... Trying to get to a custom mod name...

**Comment by budak7273** [comment]
`strings` is a Unix command and you must install an equivalent, such as the Sysinternals tool strings (which can be found [here](https://docs.microsoft.com/en-us/sysinternals/downloads/strings)), to use it on Windows. I will update the script to warn the use of this. Goz3rr and I already had it installed.

This script will only extract things from the base game pak. You might be able to extract info from other paks by changing [line 8](https://github.com/Goz3rr/SatisfactorySaveEditor/blob/master/Reference%20Materials/ExtractResources.ps1#L8) to point to a different pak file, but I haven't tried to do so myself.
