### ISSUE TITLE
Opening Save File Hangs at Please Wait...

### ISSUE THREAD

**Issue by ampingitore** [Goz3rr/SatisfactorySaveEditor#147]
When trying to open a save file in the editor it just hangs at "please wait..." and never loads the actual save file so I can edit it. It doesn't crash or anything, just never loads the save file. I can provide any details you'd need to find root cause around this. Thanks!

**Comment by aminecraftplayerx** [comment]
I'm having the same problem, I've tried removing the folder and unzipping again, etc. I know this probably isn't useful, but I downloaded the project and ran it from VS and then it worked without hanging up...

**Comment by aminecraftplayerx** [comment]
BTW I want to express my extreme gratitude for you making this tool. I can't play the game without it, the creatures are just too fast for me. So you've enabled me to play one of the better games that's come along in a long time. Thank you!

**Comment by Ryder17z** [comment]
This might be caused by the recent change in save file structure as the old files were not compressed and the current ones are

**Comment by aminecraftplayerx** [comment]
It does work 95% or more of the time, and will intermittently work even with the exact same file, so I don't think it's an issue with the compression.

**Comment by budak7273** [comment]
Could you send @Goz3rr the save file in question, either via discord or via a file upload service?

The new compressed save format should be supported as of 0.8.0.

I find it interesting that the editor was able to open the file without issue when you ran it through VS and not when compiled.

**Comment by Pherex** [comment]
I'm having a similar problem with a save file hanging at the "Please Wait."

https://drive.google.com/open?id=1IAEYsHUTSF4umm5kocukWct5r_fwPM-Y

**Comment by AnthorNet** [comment]
@Pherex, your problem is occuring because of the Transportal mod. It needs a new property read.

**Comment by Pherex** [comment]
@AnthorNet Thanks!  Unbuilt them and I could modify the save to reclaim some bugged resource nodes!

**Comment by budak7273** [comment]
The most recent update has likely fixed the issues with these mods. Could you please try to open the save again and let us know if it still locks up or errors?

**Comment by budak7273** [comment]
The save file linked by Pherex loads in the current version, and most errors of this type have been fixed already, so I propose that this issue be closed.
