### ISSUE TITLE
Crash on opening Update 3 SaveFile [v0.9.1]

### ISSUE THREAD

**Issue by barskykd** [Goz3rr/SatisfactorySaveEditor#152]
Crash log
[log.txt](https://github.com/Goz3rr/SatisfactorySaveEditor/files/4197951/log.txt)

Save file
[1.zip](https://github.com/Goz3rr/SatisfactorySaveEditor/files/4197959/1.zip)

**Comment by ANILKEN** [comment]
Same problem

Crash log
[log.txt](https://github.com/Goz3rr/SatisfactorySaveEditor/files/4198013/log.txt)

Save file
[savefile.zip](https://github.com/Goz3rr/SatisfactorySaveEditor/files/4198014/savefile.zip)

**Comment by budak7273** [comment]
Both saves load and save fine for me in 0.9.2, so you should be good after updating to the latest version.

**Comment by Goz3rr** [comment]
Thanks for providing the save files, as Rob said this should be fixed in 0.9.2
