### ISSUE TITLE
Crash on trying to view resource sink subsystem entry

### ISSUE THREAD

**Issue by vasillas** [Goz3rr/SatisfactorySaveEditor#153]
if you try to view the Persistant_level:PersistantLevel.ResourceSinkSubsystem the editor crashes on trying to display it 

[log.txt](https://github.com/Goz3rr/SatisfactorySaveEditor/files/4198795/log.txt)

**Comment by budak7273** [comment]
Could you please send the save you were editing when you encountered this error? I have yet to crash when looking at a ResourceSinkSubsystem.

**Comment by vasillas** [comment]
happens when i try to view it with this save 
[crashingsave.zip](https://github.com/Goz3rr/SatisfactorySaveEditor/files/4240402/crashingsave.zip)

**Comment by Invalid6120** [comment]
Same here.  I've tried every save file I have for update 3 and they all crash the save editor when clicking on the ResourceSinkSubsystem

**Comment by Invalid6120** [comment]
Here's the exception:
[log.txt](https://github.com/Goz3rr/SatisfactorySaveEditor/files/4270265/log.txt)

**Comment by JanB1** [comment]
Can confirm this is an issue.

The specific error/exception is "System.ArgumentOutOfRangeException", Parameter "value".

**Comment by budak7273** [comment]
I can verify this is occuring for me now as well. Thank you all for your saves and log files. 

What were you looking for/intending to modify with the ResourceSinkSubsystem? Your goal may be able to be accomplished by other means while a fix is in the works.

@JanB1 the PR/merge in the works does not resolve this issue.

**Comment by Invalid6120** [comment]
@budak7273, How about a resetting the sink counter back to zero?  If it's even possible.
