### ISSUE TITLE
Not unlock all Research

### ISSUE THREAD

**Issue by norfair00** [Goz3rr/SatisfactorySaveEditor#159]
![Research](https://files.nlab.dev/share/J6dqoqIO.jpg)

**Comment by budak7273** [comment]
The latest version (not out yet) should unlock all technologies as of 670b313. Keep your eyes on the Releases tab until then, unless you want to try to build the editor from source code. I'll comment again here when the release is put out.

**Comment by norfair00** [comment]
Thanks man. go try build
