### ISSUE TITLE
Crash with 0.9.3 when opening save

### ISSUE THREAD

**Issue by FTLNewsFeed** [Goz3rr/SatisfactorySaveEditor#161]
Trying to load my save and the application exits/crashes. Including my save for diagnostics.
[FTLNews284X.zip](https://github.com/Goz3rr/SatisfactorySaveEditor/files/4270903/FTLNews284X.zip)

**Comment by budak7273** [comment]
The application runs out of memory when I attempt to open the save on my computer. My copy of Satisfactory (experimental) also crashes when I attempt to open your save. I'm not sure I'm capable of debugging your save. Please send your `log.txt` file (in the same folder as the exe) after attempting to open the save again. I'm interested to see if the editor is also running out of memory for you, or if it's another issue.

**Comment by FTLNewsFeed** [comment]
Looks like it's an out of memory error also.
[log.txt](https://github.com/Goz3rr/SatisfactorySaveEditor/files/4274363/log.txt)

As an aside, if you want to run the save inside the game you'll need to open Engine.ini and add the following to it:
[/Script/Engine.GarbageCollectionSettings]
gc.MaxObjectsInEditor=100000000
gc.MaxObjectsInGame=100000000

Until CSS expands the uObject limit, that little workaround is needed.

**Comment by virusek20** [comment]
I noticed that for some reason we were shipping 32-bit code which was limited to 4GB RAM, but that wasn't enough to load your save. Latest master should be able to handle your save "fine", just keep in mind that it uses like 7GB of RAM.
