### ISSUE TITLE
Search for items within storage containers?

### ISSUE THREAD

**Issue by brink668** [Goz3rr/SatisfactorySaveEditor#173]
First off awesome tool!

Is it possible to search and find all the places where this item is stored? This could help located/find storage containers faster.  If this already exists would you explain how to perform such a request?
/Game/FactoryGame/Resource/Environment/Crystal/Desc_CrystalShard.Desc_CrystalShard_C

**Comment by Goz3rr** [comment]
added in v0.9.9
