### ISSUE TITLE
Not loading new beta verson

### ISSUE THREAD

**Issue by shanester990** [Goz3rr/SatisfactorySaveEditor#178]
[Shane's World_2004-011200_1587359671961.SSEbkup.zip](https://github.com/Goz3rr/SatisfactorySaveEditor/files/4501641/Shane.s.World_2004-011200_1587359671961.SSEbkup.zip)

**Comment by dawdad** [comment]
Not working for Expermentail Save Game, version 0.3.4.2 Build 119805

**Comment by conman0552** [comment]
Can confirm. Also occurring here.

**Comment by Goz3rr** [comment]
Should be fixed in 0.9.5
