### ISSUE TITLE
Add hovertext for save elements describing their assumed function

### ISSUE THREAD

**Issue by budak7273** [Goz3rr/SatisfactorySaveEditor#18]
For example, hovering over `Root > Script > FactoryGame.FGFactoryLegsComponent` would say something like "Assumed to contain data defining the height of the support legs on machines present in the save"

**Comment by virusek20** [comment]
Alright, for now it loads a dictionary from 'Types.xml' right next to the .exe, so feel free to make pull requests containing definitions from now on
If you hover over a type without a definition it'll tell you the type name and a generic message. Then you can just add the type to the 'Types.xml' file and the app should load the definition the next time you start it.
Right now the only definition is a placeholder 'Root' element, so 99.9% of things are missing.
I was also thinking about having some sort of list of untranslated types, but that's a TODO feature.
