### ISSUE TITLE
Int8Property

### ISSUE THREAD

**Issue by Sky-1633** [Goz3rr/SatisfactorySaveEditor#186]
The save editor broke with the recent Experimental update
![unknown (7)](https://user-images.githubusercontent.com/36906714/83338451-8516a480-a292-11ea-9b4e-736c700d3cb8.png)

**Comment by Spydieee** [comment]
First time firing up the save game editor and got the same thing. :'(

**Comment by Goz3rr** [comment]
This should be fixed in 0.9.7
