### ISSUE TITLE
Unknown Build Version Exception

### ISSUE THREAD

**Issue by sylvafish** [Goz3rr/SatisfactorySaveEditor#187]
[log.txt](https://github.com/Goz3rr/SatisfactorySaveEditor/files/4726059/log.txt)

[slugs everywhere - Copy.zip](https://github.com/Goz3rr/SatisfactorySaveEditor/files/4726069/slugs.everywhere.-.Copy.zip)

simply won't open save file

**Comment by Kmarkopl** [comment]
Yep, got the same. Editor need to be updated

**Comment by sylvafish** [comment]
my editor says it's already updated to the latest version though.

**Comment by Kmarkopl** [comment]
Yes. But the game was just updated yesterday. The editor last update almost a month ago.

**Comment by sylvafish** [comment]
oh geez i didn't even notice the game was updated

**Comment by thelomere** [comment]
Today another update, Game Version 123924

**Comment by Goz3rr** [comment]
This should be fixed in 0.9.7
