### ISSUE TITLE
Wrong session name parsing in a save

### ISSUE THREAD

**Issue by maksfrai** [Goz3rr/SatisfactorySaveEditor#19]
It appeared that SaveParser doesn't properly support unicode characters in session name in a save.
Specifically, in SatisfactorySaveParser:BinaryIOExtensions:ReadCharArray function value of "count" can be negative if someone will use non-latin characters in session name. To resolve this you probably should read count*2 characters as utf_16_be symbols.

To reproduce the issue:
1) Enter session name using any non-latin characters and create save.
2) Try to open the save in the editor, it will crash.

**Comment by ErenBYilmaz** [comment]
- Also happens with beacon names that contain ÖÄÜ for example ("oil" is "Öl" in german)
- Reading count*-2 characters when count is negative prevents it from crashing, but (idk if related) when i save the cheated file is corrupted (30MB instead of 46MB and endless loop when loading the game)

**Comment by Goz3rr** [comment]
Thanks for pointing this out! I have fixed the reading and writing of unicode strings in 2cd5c95.
I'll make a new release later incorporating the changes, which should fix the smaller saves and crashing as well hopefully.
