### ISSUE TITLE
Parsing an Array of Object Property not yet supported.

### ISSUE THREAD

**Issue by Fundevin** [Goz3rr/SatisfactorySaveEditor#194]
I am getting an error trying to load a save. I have attached the error message, save file, and log. Let me know if you need more info!
[Save Editor Error.zip](https://github.com/Goz3rr/SatisfactorySaveEditor/files/5144590/Save.Editor.Error.zip)

**Comment by Goz3rr** [comment]
Thanks for reporting, should be fixed in v0.9.9
