### ISSUE TITLE
Parsing an array of ObjectProperty is not yet supported

### ISSUE THREAD

**Issue by LuucEarth** [Goz3rr/SatisfactorySaveEditor#195]
My newest save file throws this error when i try to load it.

[log.txt](https://github.com/Goz3rr/SatisfactorySaveEditor/files/5178919/log.txt)

[Grass Roots.zip](https://github.com/Goz3rr/SatisfactorySaveEditor/files/5178921/Grass.Roots.zip)

**Comment by LuucEarth** [comment]
It is just this one save game that has issues

**Comment by Goz3rr** [comment]
Are you using version 0.9.9? That should've fixed this already
