### ISSUE TITLE
3/27 patch breaks

### ISSUE THREAD

**Issue by nvmax** [Goz3rr/SatisfactorySaveEditor#20]
Looks like the latest update breaks saved games, it crashes now on any saved game I have used this on, created new game got hub all unlocked planted down anything that is T7 or T8 and it seems to crash right away.

**Comment by Goz3rr** [comment]
It might be that they (intentionally) disabled some things that are supposed to be unavailable, but I'll have a look

**Comment by CoreyJ87** [comment]
Deff seems like it. If you place anything that is unavailable it throws a UE4 error saying "missing function" I believe. Pretty sure they intentionally did it after they noticed on reddit that people were doing this.

**Comment by nvmax** [comment]
yeah tried the latest version of the editor, still crashes when putting down T7 or T8 items like the nuclear power plant, damn too bad.

**Comment by letitbedone** [comment]
you can still use v95031 with the savegame editor. Works perfect for me.

**Comment by CoreyJ87** [comment]
> you can still use v95031 with the savegame editor. Works perfect for me.

Which version is that? The current? If not. How did you get to that version?

**Comment by CoreyJ87** [comment]
So im assuming this is pretty much closed? Did you test it @Goz3rr

**Comment by budak7273** [comment]
This sounds closed to me as well. The issue appears to be changes that CSS made, nothing to do with the editor itself.

**Comment by Goz3rr** [comment]
Yeah, I've finally had the time to have a look myself and nothing inherently changed in the save format that caused the editor to break.

Several changes in the game itself made some items impossible to use some items, there's not much we can do about that.

To remedy the problem I've got a few things planned which are already tracked in other issues:
- Fixing old saves by deleting now broken entities: #30 and #38 
- Preventing new saves from breaking #13 and #35
