### ISSUE TITLE
Milestone Bug

### ISSUE THREAD

**Issue by MOOOOs** [Goz3rr/SatisfactorySaveEditor#201]
Rocket no longer fly after using save editor. So i used save editor added 150 purple power slugs and 50 hard drives and when im doing research for example Tier 4 Advanced steel production somehow rocket won't fly anymore. Please fix this ruins game...

**Comment by AnthorNet** [comment]
As this is mostly a manual entry save editor, you most likely induced the bug your self?
That said as you don't details what you've done to your save and add some reproducible steps, you'll most likely hit a dead end here ;)

**Comment by MOOOOs** [comment]
I said i only added 150 purple power slugs and 50 hard drives nothing more. And it was it was added in player inventory.

**Comment by MOOOOs** [comment]
Well i found information that two tier 4 milestones gets unlocked without rocket flying so it was not bug and im closing this issue.
