### ISSUE TITLE
Change session name

### ISSUE THREAD

**Issue by K14Mua** [Goz3rr/SatisfactorySaveEditor#202]
The session name does not change.
The name of my session is "(Re) World". If you change only this line, the changes are not saved.
It is also necessary to change the line "Map options"
Specifically "?startloc=Grass Fields?sessionName=(Re) World?Visibility=SV_FriendsOnly"
In both lines I changed "(Re) World" to "Test". And we got a strange result. The session name has changed, but "Map Options" remains the same. Because of this, the save game has moved to the new "Test" world. And if you try to save it, it is saved in the old world "(Re) World".
I ask how to fix this problem.

**Comment by Ryder17z** [comment]
i think you need to rename the file itself too

**Comment by K14Mua** [comment]
> i think you need to rename the file itself too

The file itself is called "Test_save_0.sav". That is, it has already been renamed. Moreover, even if you create a new save using the "Save as..." option and enter a random name. The problem remains.

**Comment by Goz3rr** [comment]
I believe you also need to change `mReplicatedSessionName` under `/Game/FactoryGame/-Shared/Blueprint/BP_GameState.BP_GameState_C` and `mSaveSessionName` under `/Game/FactoryGame/-Shared/Blueprint/BP_GameMode.BP_GameMode_C`
