### ISSUE TITLE
an error occurred while opening the file: unable to read beyond the end of the stream

### ISSUE THREAD

**Issue by UncleSkunkApe** [Goz3rr/SatisfactorySaveEditor#205]
Hello, this is my first time using this so be kind to me, I don't know all about this stuff yet. I just got the error: an error occurred while opening the file: unable to read beyond the end of the stream. check the logs for more details.
I was trying to open my satisfactory up and continue the world I was just playing on 20hrs ago. I loaded it up and it was missing all the saves from the past 5 months. I cannot find the logs it is asking me to find, so if someone would be able to help me find those too if it might help.
 I cannot figure out what has happened as nothing has changed from last night to today other than steam had an update for the game to v.0.3.7.7- build 140083.
any help would be appreciated as this is majorly frustrating

**Comment by Ryder17z** [comment]
each save is in a different file unless you tell the game to overwrite it.
This does not apply to the 3 autosave slots for each session.

**Comment by UncleSkunkApe** [comment]
well, the only save files I have for the game are the 3 autosaves and an old manual save I did a long time ago. 9/16 to be exact. id never had any problem with the autosaves and so after that manual save never updated it with a current version. looking at the file, it is 0kb too so I am also trying to figure out how the files got wiped but the save file name never left.

**Comment by Goz3rr** [comment]
Yeah, I've seen someone else report this too, it's caused by the save file being 0 bytes like you said. I have no idea what causes it, but I'm reasonably sure the editor will never do this so it must be caused by something else. 

I will update the editor to at least give a more descriptive error in this case, but that's all I can do really.

In any case, before the save editor overwrites a file it will back up the original copy as `savename_timestamp.SSEbkup.zip` in the same folder as the save, if you don't have any other backups you can always use one of those files to restore your save.

**Comment by UncleSkunkApe** [comment]
if it helps, I do occasionally use a trainer through cheat happens. and I've never had a problem with their trainers before, so I don't think it's them, however maybe a mix of mods, save editor, and trainer might tweak some things? if there is anything else you need please let me know and ill try to get it for ya if I can.
thanks yall

**Comment by Goz3rr** [comment]
There shouldn't be any inherent incompatibilities between any of that. Are you playing on Steam or Epic? Would you also happen to know what the events were that lead up to the save being truncated?

**Comment by UncleSkunkApe** [comment]
playing on steam. no other events, just played normally like i still am to this day, maybe 3-4 hours a day or every other day. no issues or anything that popped up either
thanks yall

**Comment by Goz3rr** [comment]
Like I said I can't fix this on my end, but the editor will now give a more meaningful error message.
