### ISSUE TITLE
An error occurred while opening the file: Expected 22 bytes read but got 5

### ISSUE THREAD

**Issue by Berbioe** [Goz3rr/SatisfactorySaveEditor#208]
Just tried to edit my latest save and this happened

**Comment by Berbioe** [comment]
Turns out this error appears with save files over 513 kb, any save file below that size worked perfectly, did I miss something that says that this is how it's supposed to work?

**Comment by Goz3rr** [comment]
Could you please upload the save you're having issues with?

**Comment by Goz3rr** [comment]
This should be fixed in v0.9.13
