### ISSUE TITLE
Expected 23 bytes read but got only 5

### ISSUE THREAD

**Issue by VeverkaSK** [Goz3rr/SatisfactorySaveEditor#210]

**Comment by Goz3rr** [comment]
Could you please upload the save you're having issues with?

**Comment by VeverkaSK** [comment]
[save 23.zip](https://github.com/Goz3rr/SatisfactorySaveEditor/files/5904914/save.23.zip)
every other save throws same error (this is latest one)

**Comment by Goz3rr** [comment]
This should be fixed in v0.9.13
