### ISSUE TITLE
Game crashes when Save load

### ISSUE THREAD

**Issue by DKHolyG** [Goz3rr/SatisfactorySaveEditor#211]
Satisfactory Save Edit V. 0.9.13.0

Save game files loaded and saved (changes and no changes made to save) in the editor will make the game (Experimantal) crash on load in game

**Comment by Goz3rr** [comment]
Could you please attach the save you're having issues with?

**Comment by botflakes** [comment]
I do have the same problem. 

Save file:
[current-save.zip](https://github.com/Goz3rr/SatisfactorySaveEditor/files/5979194/current-save.zip)

It the most recent experimental build and I'm using the latest of your Release

**Comment by Vykel** [comment]
Same problem here. I edit a save and load it in the game and it crashes. Even if I try to load the edit save with your editor it crashes with this message : "An error occurred while opening the file : Expected 5 bytes read but got 19"
Here the corrupted save :
[Save.zip](https://github.com/Goz3rr/SatisfactorySaveEditor/files/6134182/Save.zip)

Last experimental version with last release of your editor.

**Comment by Goz3rr** [comment]
This should be fixed in v0.9.14
