### ISSUE TITLE
Parsing an array of IntProperty is not yet supported.

### ISSUE THREAD

**Issue by AlexFielder** [Goz3rr/SatisfactorySaveEditor#212]
Hi,

I just tried opening the attached modded save using version 0.9.13 and got the above error.

Attached are the log and save files as requested.

Thanks,

Alex.
[log.txt](https://github.com/Goz3rr/SatisfactorySaveEditor/files/6060922/log.txt)
[PreUpdate4_094.zip](https://github.com/Goz3rr/SatisfactorySaveEditor/files/6060924/PreUpdate4_094.zip)

**Comment by Goz3rr** [comment]
This should be fixed in v0.9.14
