### ISSUE TITLE
Feature : Remove Giant Flying Manta

### ISSUE THREAD

**Issue by progz** [Goz3rr/SatisfactorySaveEditor#216]
Hi, 
I want to remove the 2 Giant Flying Manta in Satisfactory World.
They seems to not be considred as creatures but as entities. I can't find which entities to remove in the save to remove them.

Maybe you could make a cheat option : Remove Giant Flying Manta to be easier for people like me.

Best regards,

**Comment by Goz3rr** [comment]
I don't think anything about them is saved, so it's not possible to remove them with a save editor. You would have to use a game mod for that most likely.

**Comment by Ryder17z** [comment]
there is a mod called Invisible Flying Manta 
give it a try.
