### ISSUE TITLE
No build cost/No power cost does not work

### ISSUE THREAD

**Issue by JayTheGithubUser** [Goz3rr/SatisfactorySaveEditor#219]
Exactly what the title says

**Comment by jmacwhyte** [comment]
This needs a lot more information if you want to see any action on it. What did you try? And what was the result?

**Comment by Ryder17z** [comment]
No power still requires buildings to be connected to power poles.

**Comment by JayTheGithubUser** [comment]
So, it started working again today for no apparent reason. I had done everything I was supposed to? I had connected them to a power grid, saved, quit, restarted satisfactory, and it didnt work. I didn't do anything and then it just started working today, idk what happened
