### ISSUE TITLE
Can't open my save 

### ISSUE THREAD

**Issue by GMMG12** [Goz3rr/SatisfactorySaveEditor#225]
![Screenshot 2021-05-21 215854](https://user-images.githubusercontent.com/84599830/119193490-fb06b380-ba81-11eb-8508-01053fa3495b.png)

**Comment by Ryder17z** [comment]
needs more information, like the log file if it was created, what game version or a savegame or something

**Comment by Goz3rr** [comment]
Assuming this was fixed long ago
