### ISSUE TITLE
Editor crash on save file open

### ISSUE THREAD

**Issue by AlexFielder** [Goz3rr/SatisfactorySaveEditor#227]
Game version: 155370 (Experimental branch)
Editor Version: 0.9.17
Steps to reproduce: Open attached save file in above version.
Log attached: [log.txt](https://github.com/Goz3rr/SatisfactorySaveEditor/files/6616576/log.txt)
Save file attached: [Pre-Flush-2021-06-07.zip](https://github.com/Goz3rr/SatisfactorySaveEditor/files/6616583/Pre-Flush-2021-06-07.zip)

**Comment by Goz3rr** [comment]
This should be fixed in 0.10.0
