### ISSUE TITLE
Error message when trying to open save

### ISSUE THREAD

**Issue by DevilAdvocate02** [Goz3rr/SatisfactorySaveEditor#231]
An error occurred while opening the file:
Expected 1977 bytes read but got 1981

This has been ongoing for a few weeks now.
Save file is not giving any issues when loading.

[log.txt](https://github.com/Goz3rr/SatisfactorySaveEditor/files/6900926/log.txt)
[A New Start_2412-230547.zip](https://github.com/Goz3rr/SatisfactorySaveEditor/files/6900931/A.New.Start_2412-230547.zip)

**Comment by Goz3rr** [comment]
This should be fixed in 0.10.0
