### ISSUE TITLE
Error on Open: "Unknown ETextHistoryType Transform"

### ISSUE THREAD

**Issue by johnvilsack** [Goz3rr/SatisfactorySaveEditor#232]
Logs and save attached. Problem is reproducible. Appears to be an issue with the Really Simple Signs or Remote Factory mod.

[Unicron.zip](https://github.com/Goz3rr/SatisfactorySaveEditor/files/6919324/Unicron.zip)
[log.txt](https://github.com/Goz3rr/SatisfactorySaveEditor/files/6919318/log.txt)

**Comment by catonthekbd** [comment]
Same issue for me - I have RSS installed, but not Remote Factory

**Comment by Goz3rr** [comment]
This should be fixed in 0.10.0
