### ISSUE TITLE
Error Loading modded save. "Non negative number required" parameter: count.

### ISSUE THREAD

**Issue by AlphaLlama** [Goz3rr/SatisfactorySaveEditor#234]
As the title says, modded game save won't load. save and log files included. if needed i can include a list of mods being used. 
[build1.zip](https://github.com/Goz3rr/SatisfactorySaveEditor/files/6950326/build1.zip)
[log.txt](https://github.com/Goz3rr/SatisfactorySaveEditor/files/6951304/log.txt)

**Comment by Goz3rr** [comment]
This should be fixed in 0.10.0
