### ISSUE TITLE
TextProperty is not displaying value when historyType = 255

### ISSUE THREAD

**Issue by GrimNotepad** [Goz3rr/SatisfactorySaveEditor#236]
made the following change to TextPropertyViewModel.cs
Satisfactory.SaveEditor
SatisfactorySaveEditor.ViewModel.Property.TextPropertyViewModel
& 
SatisfactorySaveEditor.ViewModel.Property.ApplyChanges

added a case for NoneTextEntry.

I did not test this extensively, i only cared about fixing my beacon names in my save file, but i wanted to point out that prior to this it was not showing me the name of my beacons, and now it does and it does save it back properly and i was able to load the save file into the game and see the new text change on my beacon

        public TextPropertyViewModel(TextProperty textProperty) : base(textProperty)
        {
            model = textProperty;

            switch(textProperty.Text)
            {
                case BaseTextEntry baseText:
                    value = baseText.Value;
                    break;
                case NoneTextEntry baseText:
                    value = baseText.CultureInvariantString;
                    break;
            }
        }

        public override void ApplyChanges()
        {
            switch (model.Text)
            {
                case BaseTextEntry baseText:
                    baseText.Value = value;
                    break;
                case NoneTextEntry baseText:
                    baseText.CultureInvariantString = value;
                    break;
            }
        }

**Comment by Goz3rr** [comment]
Thanks, I've merged it in for the next release 👍
