### ISSUE TITLE
Unable to read beyond the end of the stream

### ISSUE THREAD

**Issue by Tyranikus** [Goz3rr/SatisfactorySaveEditor#237]
Message of "Unable to read beyond the end of the stream" pops up when trying to open my save
[log.txt](https://github.com/Goz3rr/SatisfactorySaveEditor/files/7198917/log.txt)
[Save.zip](https://github.com/Goz3rr/SatisfactorySaveEditor/files/7198923/Save.zip)
.

**Comment by Goz3rr** [comment]
This should be fixed in 0.10.0
