### ISSUE TITLE
Unlock map doesnt seem to work?

### ISSUE THREAD

**Issue by CoreyJ87** [Goz3rr/SatisfactorySaveEditor#24]
Even before 3/27

**Comment by Goz3rr** [comment]
You might have to try it in combination with unlock all research

**Comment by budak7273** [comment]
I have used it without issue, even after just completing tier 0. Could you attach your save file? 

Are you sure you're saving your changes after unlocking the map? That's the first thing I can think of that would cause it.

**Comment by CoreyJ87** [comment]
disregard. I tried it again today and it worked fine. I must have not saved it or something. Thanks guys.
