### ISSUE TITLE
Crashing with OOM errors in event viewer

### ISSUE THREAD

**Issue by CoreyJ87** [Goz3rr/SatisfactorySaveEditor#25]
Used it the other day and actually unlocked everything and the map. Then went back and just unlocked the map. Finally got to end game where I decided to actually unlock the other stuff. Now everytime I open this save in the app it crashes the app with no errors but in the event viewer is says OOM. Seems like the app is running out of memory although my computer is not. I have 32gb with maybe 7 gigs used
[oom.zip](https://github.com/Goz3rr/SatisfactorySaveEditor/files/3026160/oom.zip)

One thing I did do since the last save it works. Was change the colors of all the buildings. Not sure if that matters or not.

I was able to get it to work with this one that was from earlier that I had not changed the colors. Although anytime I place any of the unlocked stuff the game crashes. This been happening with anyone else? I tried to place train tracks and a radar tower.
[wat.zip](https://github.com/Goz3rr/SatisfactorySaveEditor/files/3026168/wat.zip)

**Comment by thevipe** [comment]
do you have any automated trucks on creating a path at the moment it makes the game lag and game save get bigger which then makes loading take forever or crashes your game, also 

> anytime I place any of the unlocked stuff the game crashes
bump on issues #20

**Comment by CoreyJ87** [comment]
I have one truck down. I was able to load it into the save editor with the truck in both saves. Although like I said placing anything causes the game to crash. I think it was changing the colors of everything probably bloated my save. Just to clarify. There's 2 different issues one is loading the save into the actual save editor. and one is the crashing that happens when placing any new tier object. I heard some rumblings on reddit that they may have removed the items from the EA version of the game. Not sure if thats true or not.

**Comment by thevipe** [comment]
I have the same issue with loading a save into the editor and placing the objects and after that last patch does crash the game so yea I don't know if its the save editor or they removed stuff so we cant cheat them in

**Comment by Goz3rr** [comment]
Hey, thanks for the report.

As for the OOM problems, they should be fixed in the latest release so please give that a try.
I hadn't implemented colors yet and the editor was unable to handle them properly.

**Comment by CoreyJ87** [comment]
Ah gotcha. So my suspicion was correct. I had noticed your commit was messing with colors. So that made me think about it.
