### ISSUE TITLE
SatisfactorySafeParser (...) UnknownBuildVersionException

### ISSUE THREAD

**Issue by Redtimmystone** [Goz3rr/SatisfactorySaveEditor#257]
When i try to load it it dosent work

**Comment by Hamza-Hanif-786** [comment]
i also have same problem

**Comment by SolomonCM** [comment]
same here, program needs updating to handle changes to save file in update 6

**Comment by cowlinator** [comment]
Same. There are also a bunch of duplicate issues opened about this. The master branch hasn't been touched in 8 months. I suspect this repo might be dead.

**Comment by budak7273** [comment]
More info in #267
