### ISSUE TITLE
Save editor crashes when trying to load sav

### ISSUE THREAD

**Issue by thevipe** [Goz3rr/SatisfactorySaveEditor#26]
I have a pretty good built base and I have no idea why but when I try to load the save into the editor, it crashes (uploading save for someone to debug it)

I was able to edit it in v2 but not now in v3

[DontBreakv3.zip](https://github.com/Goz3rr/SatisfactorySaveEditor/files/3026206/DontBreakv3.zip)

**Comment by Goz3rr** [comment]
Please give the latest released version a try, should fix it.
