### ISSUE TITLE
Error opening save file

### ISSUE THREAD

**Issue by DogsAndCats7429** [Goz3rr/SatisfactorySaveEditor#264]
I just downloaded it and an error immediately here is the log file

[log.txt](https://github.com/Goz3rr/SatisfactorySaveEditor/files/10016183/log.txt)

**Comment by dorey973** [comment]
Same error, it's saying 'SatisfactorySaveParser.Exceptions.UnknownSaveVersionException', so I guess it need to be update for experimental

**Comment by budak7273** [comment]
More info in #267
