### ISSUE TITLE
error opening saves

### ISSUE THREAD

**Issue by Tiertheflash** [Goz3rr/SatisfactorySaveEditor#265]
i tried to open a save then it says SatisfactorySaveParser.Exceptions.UnknownSaveVersionException: Exception of type 'SatisfactorySaveParser.Exceptions.UnknownSaveVersionException' was thrown.
   at SatisfactorySaveParser.Save.FSaveHeader.Parse(BinaryReader reader) and i dont know what to do
[log.txt](https://github.com/Goz3rr/SatisfactorySaveEditor/files/10079893/log.txt)

**Comment by budak7273** [comment]
More info in #267
