### ISSUE TITLE
How does the Resource Spawner work?

### ISSUE THREAD

**Issue by EpicLPer** [Goz3rr/SatisfactorySaveEditor#56]
The option to select what you want is self explanatory but how can I increase the amount it gives me? It's at zero and I tried every key possible but it just won't change...

**Comment by Goz3rr** [comment]
The amoun is just a label that shows how much items have been spawned, if you want to get an item out just connect a belt.

**Comment by EpicLPer** [comment]
Ah, thanks a lot!
