### ISSUE TITLE
Automatically create backups of saves when they are opened

### ISSUE THREAD

**Issue by budak7273** [Goz3rr/SatisfactorySaveEditor#64]
Perhaps make a subfolder in the saves folder and copy the save there with `.BAK` or similar appended to the file extension.

**Comment by Goz3rr** [comment]
Yeah we should definitely do this, although we could probably do it on save instead of open. How do we want to handle duplicate backups?

**Comment by budak7273** [comment]
Perhaps append the date and time to the save file? Maybe `.BAK#`? Regardless, we should probably limit it to only a few backups per save. 

The save files compress exceedingly well, so we may want to consider zipping the backups as well.

**Comment by budak7273** [comment]
Closed by #111
