### ISSUE TITLE
Modify amount of item X

### ISSUE THREAD

**Issue by xsimtomx** [Goz3rr/SatisfactorySaveEditor#82]
Hi there,

Since there is a bug in the current Experimental Release where you can lose entire stacks of items (I lost 40 Power Shards) I was wondering if it's possible to add a function where you can just modify the amount of items you have of an item. Like, it would be very handy to add back the 40 Power Shards I lost without the need to fully edit my save file. Or is that simply not possible?

Anyway, thanks for all the work you've done so far!

**Comment by Ryder17z** [comment]
I lost 11 power shards due to the same bug 👎

**Comment by fleeting-aardvark** [comment]
I think the bug could be related to having more than the stack allows.  A workaround for the disappearing stack is to transfer the stack to another container.  However, if you have more than the stack allows, then only the top number of items for that stack will still be there.  Still not sure why it is disappearing if you hit the sort button before moving any item.

**Comment by xsimtomx** [comment]
I was able to "retrieve" the lost shards by using a Cheat Engine table.

**Comment by fleeting-aardvark** [comment]
> 
> 
> Hi there,
> 
> Since there is a bug in the current Experimental Release where you can lose entire stacks of items (I lost 40 Power Shards) I was wondering if it's possible to add a function where you can just modify the amount of items you have of an item. Like, it would be very handy to add back the 40 Power Shards I lost without the need to fully edit my save file. Or is that simply not possible?
> 
> Anyway, thanks for all the work you've done so far!

Yes it is possible to modify the amount of items you have in your inventory.
Using the editor, go to the following location:
[Save Name] > Game > FactoryGame > Character > Player > Char_Player.Char_Player_C

At that location will be a list of players in the game.  Your character *should* be:
Persistent_Level:PersistentLevel.Char_Player_C_0

Under that character's properties will be several objects.  The one you are interested in is "mInventory". There is a jump button to the right.  That will take you to your inventory.

From there, you will go to the "mInventoryStacks" property.  That is where you can tweak the amounts currently in your inventory.  The item type should give you an idea of what you are carrying.

**Comment by xsimtomx** [comment]
Oh, I didn't know this was already included in the editor. Thanks!

**Comment by Goz3rr** [comment]
Yeah, it's on the to-do list to make this more user friendly, but the way @fleeting-aardvark described it is currently the way to do this.
