### ISSUE TITLE
Empty recovery chests that cant be removed

### ISSUE THREAD

**Issue by DianaNites** [Goz3rr/SatisfactorySaveEditor#84]
If you kill dummy characters, but they don't have anything in their inventory, the recovery chest they drop can't be removed, nothing happens when you attempt to open it.

**Comment by Goz3rr** [comment]
This should be fixed in release 0.5.1 (https://github.com/Goz3rr/SatisfactorySaveEditor/releases/tag/0.5.1) thanks to @mircearoata
