### ISSUE TITLE
Killing dummies crashes the editor

### ISSUE THREAD

**Issue by Ryder17z** [Goz3rr/SatisfactorySaveEditor#87]
No error message, just a silent crash if i hit "Kill Dummy Players" on this particular savegame

[crashingdummy.zip](https://github.com/Goz3rr/SatisfactorySaveEditor/files/3158168/crashingdummy.zip)

**Comment by mircearoata** [comment]
Cause: when there aren't any crates in the save, there is no "BP_Crate.BP_Crate_C" object, since the game does not save defaults/empties. Fixed now.

And your save (without dummy players): [crashingdummy.zip](https://github.com/Goz3rr/SatisfactorySaveEditor/files/3158308/crashingdummy.zip)
