### ISSUE TITLE
Cheat Build

### ISSUE THREAD

**Issue by voctavio** [Goz3rr/SatisfactorySaveEditor#90]
Is there anyway to add the cheat build in game, without unlocking all milestones? If not, this option should be separated. And option should be added separately.

**Comment by Goz3rr** [comment]
It's on the to do list to make unlock selection possible, but for now you can either manually edit your save or edit the research.xml file to only contain the things you want to unlock.

**Comment by budak7273** [comment]
Unlock selection is coming with the rewrite.

**Comment by Goz3rr** [comment]
Cheats were completely removed from the game so nothing we can do here anymore
