### ISSUE TITLE
Peaceful Mode

### ISSUE THREAD

**Issue by supremacy2k** [Goz3rr/SatisfactorySaveEditor#91]
Is it possible to add the ability to enable peaceful mode?
Meaning, killing all hostiles in the game?

I checked under Game -> FactoryGame -> Character -> Creature -> Enemy and BP_CreatureSpawner, which has a "WasKilled" checkbox, but i can't find a single one that is ticked.

**Comment by mircearoata** [comment]
I added this in my fork a few days ago. I will make a pull request after I check the code again

**Comment by supremacy2k** [comment]
Awesome!
Just remember not to kill Lizard Doggos and Whales :D

**Comment by mircearoata** [comment]
Well... unfortunately mSpawnData has the Creature property empty, so I cannot check the animal's type.
But there are CreatureSpawner and EnemySpawner. Is CreatureSpawner only friendly/neutral?

**Comment by supremacy2k** [comment]
I honestly don't know, it consists of 1852 objects in my savegame, and it doesn't say what type of creature it is.

I has info like:
Entity Name: Persistent_Exploration:PersistentLevel.BP_CreatureSpawner104
Coords, 
ParentObjectName/Root (Both Empty), 
Creature (Parent, Target, both empty), 
Was Killed (unchecked checkbox),
KilledOnDayNr, which is all -1, 
and then a random seed number.

**Comment by mircearoata** [comment]
Probably Wildlife contains all spawned peaceful animals.
Can you upload a save with tamed doggo and some whales, to check what I shouldn't delete? I already deleted all my animals...

**Comment by supremacy2k** [comment]
Sure can, but since we can't tame whales there nothing i can do on that front.

http://www.alabit.dk/supremacy2k.rar
This one contains 6 tamed doggos.

**Comment by mircearoata** [comment]
I still ended up creating a new save to check on, because I needed all the animals so that I don't miss enemies / kill doggos. Works now, PR #92

**Comment by supremacy2k** [comment]
Fantastic! Thank you. :)

**Comment by Goz3rr** [comment]
Thanks, I'll make a new release later today with this in it

**Comment by supremacy2k** [comment]
I compiled my own to test it.
Went to an area where i had been at the outskirts of it, and it was mostly empty.

Found 2 boars, and TONS of bees.

**Comment by mircearoata** [comment]
Where exactly did you go?

**Comment by supremacy2k** [comment]
In upper left corner of the map (satisfactorymap.com), there is 2 geysers.
In that area.

**Comment by mircearoata** [comment]
I saw the bees, and they are called CreatureSpawner so they don't get deleted... The only thing you can do from the save editor is to delete both creature and enemies (or check each of the CreatureSpawner locations to see if it is friendly or enemy), but as a mod you could delete enemies when they show up, and set as killed. 
Also, what are "boars"?

**Comment by supremacy2k** [comment]
What i call boars are called Hogs in-game.
https://satisfactory.gamepedia.com/Fluffy-tailed_Hog

The reason i posted about the 2 hogs, is because having this cheat becomes kinda pointless, if not most or all enemies are spawned at the beginning of the map, making a "kill all" function way less effective.

I'll do some more testing later tonight (6pm my time atm), and see if i can find an area where I'm 100% sure i have never been.

**Comment by mircearoata** [comment]
I even killed everything and the crabs still spawned. I think is the game's save/load issue here. I had some crabs respawn in my save too. I will try killing them ingame, save and reload to check if they respawn

**Comment by supremacy2k** [comment]
I think they respawn if you don't collect what they drop.
I had it happen a few times, and as long it's just the flying crabs, we have something for sniper practice :)

**Comment by mircearoata** [comment]
Killed ingame, reloaded, didn't respawn, used the cheat again (after killing ingame), reloaded, respawned. My guess is that is the KilledOnDayNumber

**Comment by supremacy2k** [comment]
They don't make it easy, do they?
Can you set KilledOnDayNumber to.. 1 or something?
It seems they use -1 various places for inf or N/A if you will.

**Comment by mircearoata** [comment]
I set it to current_day-1 and it worked

**Comment by supremacy2k** [comment]
Well, as long as they stay gone, I'm happy :D

**Comment by mircearoata** [comment]
I mean... you can always edit more friendly animals in your save if you want to. If I bug report that enemies are marked as creatures will it get fixed?

**Comment by supremacy2k** [comment]
Not likely.

At least not anytime soon, i think :)
But as long as only crabs remains I'm happy, and will suit most "peaceful mode" use cases i think :)

**Comment by mircearoata** [comment]
I don't know if only crabs remain, but I pushed a fix (delete all) to my fork anyway (in case other animals appear)

**Comment by supremacy2k** [comment]
Thy shall not respawn! :D 
I'll check the update later, thanks :)

**Comment by MiiKe999** [comment]
Hi Goz3rr, after clicking delete all enemies and saving it, when I restart the game, all enemies are spawning back like Hogs and those fire throwing creatures. I don't know how this works, I mean if they respawn, what's the use of this cheat? The hostiles are so annoying in this game. Kindly reply.

**Comment by mircearoata** [comment]
In what area does this happen? Could you upload a save?

**Comment by MiiKe999** [comment]
Then how to kill all animals as I don't care of animals in this game. Please explain as I'm not that familiar with save editor.

**Comment by mircearoata** [comment]
The same thing you did before, but use this version (it kills all): https://github.com/mircearoata/SatisfactorySaveEditor/releases/tag/0.5.2-delete-enemies

**Comment by MiiKe999** [comment]
OK. One last question, will it delete animals from areas I have never visited on the map also? Because that is also which I don't want to deal when visiting new places. I have seen animals with 0.5.3 save editor delete version when going to new places. Thanks!

**Comment by mircearoata** [comment]
It sets as killed everything that is spawnable (including unvisited areas), but if the devs add more enemies, you will need you to do save edit again for the added enemies

**Comment by supremacy2k** [comment]
I just visited area i had never been to last night.
And it was full of enemies.

It saddens me it's so darn hard to kill them off.
I think what's happening, is that as long as there is no player structures, they will keep respawning, like they normally do.

No matter how many times we kill them off in the savefile. :/

**Comment by mircearoata** [comment]
Ok... I have another idea: move all the spawns below the map. I will try this later

**Comment by supremacy2k** [comment]
But if that leaves them falling to their death, won't they just respawn again?

**Comment by MiiKe999** [comment]
@supremacy2k Have you used 0.5.3 or 0.5.3?

**Comment by mircearoata** [comment]
0.5.2 meaning my version

@supremacy2k only players die from falling from what I understand, anything else sits on something at around Z 0. Also I'll try to set the spawners position, meaning that it will never be in player's range so it won't spawn

**Comment by supremacy2k** [comment]
MiiKe999, I'm testing on 0.5.3.0
Mircearoata, There was something i didn't know. :D 
But i look forward to more testing. :)

More Doggos are always good, my 6 is regular slug hunters, it's amazing :D

**Comment by mircearoata** [comment]
Try with my version, it has the 1 billion to KilledOnDayNo, which I don't think was added in the pull request in time. If it still happens I will try to move them under the map

**Comment by supremacy2k** [comment]
Okey, I downloaded your version, compiled it, backup'ed my savegame, and I'm gonna try it, and cross the map.

I'll update this post, when I'm done reaching the new area.

**Comment by mircearoata** [comment]
Delete-animals branch

**Comment by supremacy2k** [comment]
Yeah i found it. :)

**Comment by supremacy2k** [comment]
I've been around... like a lot.
Not even the flying crabs remains :D

**Comment by MiiKe999** [comment]
@mircearoata The delete cheat in 0.5.2 is superb and I am really thankful for the work you put in, never had enjoyed this free roam building in satisfactory as I am enjoying right now. No animals, no bull-crap; only factories and exploration for minerals.

**Comment by mircearoata** [comment]
@MiiKe999 felt the same after making it. If it works, I will try to add the compensatory Lizzard Doggos and pull request the fixes

**Comment by mircearoata** [comment]
3 compensatory Lizzard Doggos and fix for the respawning crabs are in PR #98. Hopefully Coffee Stain adds the spawner type in some update, but until then, use the cheat more times if you want more doggos. Then we might need a building to auto-collect from doggos to automate slugs :)

**Comment by supremacy2k** [comment]
While looking for sulfur nodes today, i just ran into 3 hogs.
I think the game respawns some of them (they are the first ones i see)

Thought I'd let you know.

**Comment by mircearoata** [comment]
I made an animal map (https://imgur.com/a/N4Zcf16) from your save file and the area you were in has no animal spawns saved. Some areas look too peaceful to be true (NE, around center, and your area too). Either it doesn't save the spawns in areas you didn't visit (which makes the peaceful cheat annoying to use every time you explore), or... just doesn't save some (which is even worse and unlikely).
I'll do a map on a new save, maybe in each of the spawn locations

**Comment by supremacy2k** [comment]
I uploaded my latest save, i used the cheat twice, before finding those animals.
Head north-east past the crater in the south, and you'll encounter them

http://www.alabit.dk/supremacy2k-savegame.rar

**Comment by mircearoata** [comment]
I moved the spawns under the map and it looks like it worked (on the first save you uploaded). Went all around the sulfur and uncovered pretty much all the area between the factory and the sulfur (I think I went the same path you went) and found nothing. Pushed the update to delete-animals branch on my fork.

**Comment by MiiKe999** [comment]
@mircearoata Moving them under the map will be useful or we will hear animal sounds from underground? If I use this update on the same save in which I had used your delete-cheat, will it spawn dead animals underground afresh or I am not getting it? Because my save is same. 
So, Coffee Stain is really pushing hard to make animal dominance on this factory building sim, aren't they?

**Comment by mircearoata** [comment]
I doubt you will hear anything from around 1000 kilometer under the map, and I doubt that's in range to spawn too. I don't think they actually did this on purpose, but rather that's the way they check if an animal should spawn and maybe there's something I'm missing between the unspawned and killed, but I can't figure what.

**Comment by supremacy2k** [comment]
I went to this sulfur node: https://imgur.com/a/u2rp8W6
Which is hidden in a cave with a purple slug.
In that cave, i found a cat.

Not sure how it managed to stay above ground, but there is was. :D

**Comment by mircearoata** [comment]
Ok, I really want to talk to the devs. EnemySpawner spawns doggos and CreatureSpawner spawns enemies... Maybe they did it on purpose actually...

>CreatureSpawner845_30 spawnpoint moved to Z -949.5654
CreatureSpawner845_30 has spawned Char_CaveStinger_C_0 Z: -1240.742
CreatureSpawner846 has spawned Char_Spitter_C_7 Z: -1E+08
CreatureSpawner848 has spawned Char_Spitter_Alternative_C_1 Z: -1E+08
CreatureSpawner849 has spawned Char_Spitter_Small_C_0 Z: -1E+08
CreatureSpawner849 has spawned Char_Spitter_Small_C_1 Z: -1E+08
CreatureSpawner849 has spawned Char_Spitter_Small_C_2 Z: -1E+08
EnemySpawner473 has spawned Char_SpaceRabbit_C_1 Z: 312.328

After a quick check: all the spawns got back to their location, but many kept their spawnpoints under the map. Maybe for some spawnpoints 1000 km was too under the map to be realistic and the game reset the location? I'll try something less.

Also, what animal is a Walker?

**Comment by mircearoata** [comment]
So: after more than 1.5GB of edited save files and 6 tries, the spider is gone. I added back killing the animals and it moves the spawns under map relative to the current position (most of the ones that came back were 5000 something and they were moved to -100000...). Also setting killeddaynumber to something related to distance to player, which might help too.
I really hope it works, because it started as "I don't like animals in this game, can I delete them?" and now it is a 53 comment thread...

**Comment by supremacy2k** [comment]
Walker has to be this one: https://satisfactory.gamepedia.com/Land_Whale_Long-legs

And yes, it started like "I wan't a peaceful mode" to a Terminator like survival game, where they just keep coming back :D

**Comment by mircearoata** [comment]
Since 5 days passed you finding (or at least writing that you found) animals respawned, did the last version work? If so, I will PR and hope it will be the last one for this cheat

**Comment by supremacy2k** [comment]
Once in a while I find a Lone spider in a cave, but thats it.

So overall, it's a 99.99% success :-D

**Comment by budak7273** [comment]
Closed by #118 . I suspect that Update 3 may introduce some issues with new spawning locations and the new respawn system, so feel free to reopen this issue if you encounter further issues.
