### ISSUE TITLE
Question: did CSS remove the later tier content?

### ISSUE THREAD

**Issue by xsimtomx** [Goz3rr/SatisfactorySaveEditor#93]
I noticed that I can no longer access the MK5 & 6 conveyer belts, nor the later tier buildings (like the Nuclear Reactor and trains). There are however still some unreleased walls available when using the save editor but that's all.

Is this something you've encountered as well?

**Comment by mircearoata** [comment]
Yes, they removed everything that is not yet achievable about a month ago

**Comment by xsimtomx** [comment]
> Yes, they removed everything that is not yet achievable about a month ago

Okay, that's what I thought. I guess we'll have to have some more patience then!

**Comment by Goz3rr** [comment]
There were removed from the game to make the download smaller
